### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by adeola003** [RHK-MICROVERSE/Conference#4]
Nice project, but there are some little things that could improve your code if fixed:
- Line 8: Use single quotations instead of double in speakers.js;
- Line 22: Avoid using trailing spaces;
- Line 35: Give space after the colon;
- Line 66: Lining space required.

**Comment by RHK-MICROVERSE** [comment]
All the above issues have been resolved properly. I really appreciate your keen eyes which helped me a lot to understand the space and line issues.
